# Generated by Django 5.1.3 on 2024-11-13 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Date",
            fields=[
                ("date_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(unique=True)),
                ("year", models.IntegerField(max_length=4)),
                ("month", models.IntegerField(max_length=2)),
                ("quarter", models.IntegerField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="region",
            field=models.CharField(
                choices=[("N", "North"), ("W", "West"), ("S", "South"), ("E", "East")],
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="date_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policies",
                to="analysis.date",
            ),
        ),
    ]
