# Generated by Django 5.1.3 on 2024-11-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_date_alter_customer_gender_alter_customer_region_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="month",
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name="date",
            name="quarter",
            field=models.IntegerField(default=4, max_length=1),
        ),
        migrations.AlterField(
            model_name="date",
            name="year",
            field=models.IntegerField(default=2024, max_length=4),
        ),
    ]
