# Generated by Django 5.1.3 on 2024-11-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_alter_date_month_alter_date_quarter_alter_date_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="total_policies",
            field=models.IntegerField(default=0),
        ),
    ]
