# Generated by Django 5.1.3 on 2024-11-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0004_policy_total_policies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("Male", "M"), ("Female", "F")], max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="region",
            field=models.CharField(
                choices=[("North", "N"), ("West", "W"), ("South", "S"), ("East", "E")],
                max_length=7,
            ),
        ),
    ]
